# On branch push, download the windows testing bundle build and run it.

name: windows

on:
  push:
    branches:
      - master
      - bors/staging
      - bors/trying
      - 'release/v*'
  pull_request:

jobs:
  setup:
    runs-on: windows-2016
    name: Download testing bundle
    steps:
      - name: 'Wait for Hydra build'
        uses: rvl/hydra-build-products-action@master
        id: hydra
        with:
          hydra: 'https://hydra.iohk.io'
          jobs: 'linux.windows.cardano-wallet-tests-win64'
      - name: 'Fetch Windows testing bundle'
        shell: powershell
        run: |
          $output = "cardano-wallet-tests-win64.zip"
          Invoke-WebRequest -Uri ${{ steps.hydra.outputs.buildProducts }} -OutFile $output
          Expand-Archive -LiteralPath $output -DestinationPath .
          Get-ChildItem
      - name: Save files
        uses: actions/upload-artifact@v2
        with:
          name: cardano-wallet-tests-win64
          path: "**/*"

  cardano-wallet-core-test-unit:
    name: 'cardano-wallet-core:unit'
    needs: setup
    runs-on: windows-2016
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: cardano-wallet-tests-win64
      - run: '.\\cardano-wallet-core-test-unit.exe --color --jobs 1 --skip /Cardano.Wallet.DB.Sqlite/ +RTS -M2G -N2'

  cardano-wallet-test-unit:
    name: 'cardano-wallet:unit'
    needs: setup
    runs-on: windows-2016
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: cardano-wallet-tests-win64
      - run: '.\\cardano-wallet-test-unit.exe --color'

  cardano-wallet-cli-test-unit:
    name: 'cardano-wallet-cli:unit'
    needs: setup
    runs-on: windows-2016
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: cardano-wallet-tests-win64
      - run: '.\\cardano-wallet-cli-test-unit.exe --color'

  text-class-test-unit:
    name: 'test-class:unit'
    needs: setup
    runs-on: windows-2016
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: cardano-wallet-tests-win64
      - run: '.\\text-class-test-unit.exe --color'

  cardano-wallet-launcher-test-unit:
    name: 'cardano-wallet-launcher:unit'
    needs: setup
    runs-on: windows-2016
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: cardano-wallet-tests-win64
      - run: '.\\cardano-wallet-launcher-test-unit.exe --color'
        continue-on-error: true

  cardano-wallet-test-integration:
    name: 'cardano-wallet:integration'
    needs: setup
    if: ${{ startsWith(github.ref, 'refs/heads/bors/') || startsWith(github.ref, 'refs/heads/release/v') }}
    runs-on: windows-2016
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: cardano-wallet-tests-win64
      - run: '.\\cardano-wallet-test-integration.exe --color'
        timeout-minutes: 60

  finish:
    name: Finish
    runs-on: windows-2016
    if: always()
    needs:
      - cardano-wallet-core-test-unit
      - cardano-wallet-test-unit
      - cardano-wallet-cli-test-unit
      - text-class-test-unit
      - cardano-wallet-launcher-test-unit
      - cardano-wallet-test-integration
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: "Advance windows-tests-pass and all-tests-pass branches"
        if: github.ref == 'ref/heads/master'
        shell: bash
        run: 'bash .buildkite/push-branch.sh windows-tests-pass linux-tests-pass all-tests-pass'
